src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'float')]
    #[Assert\NotNull]
    private ?float $totalprice = null;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Assert\NotNull]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $adresse = null;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: OrderItem::class, cascade: ["remove"])]
    private Collection $orderItem;

    public function __construct()
    {
        $this->orderItem = new ArrayCollection();
        $this->setTotalprice();
    }

    public function __toString()
    {
        return (string) $this->id;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItem(): Collection
    {
        return $this->orderItem;
    }

    public function addOrderItem(OrderItem $orderItem): self
    {
        if (!$this->orderItem->contains($orderItem)) {
            $this->orderItem->add($orderItem);
            $orderItem->setOrder($this);
        }
        $this->setTotalprice();

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItem->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getOrder() === $this) {
                $orderItem->setOrder(null);
            }
            $this->setTotalprice();
        }

        return $this;
    }

    public function getTotalprice(): ?float
    {
        return $this->totalprice;
    }

    public function setTotalprice(): self
    {
        $total = 0;
        foreach ($this->getOrderItem() as $item) {
            if ($item->getProd() !== null) {
                $total += $item->getQty() * $item->getProd()->getPrice();
            }
        }
        $this->totalprice = $total;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("product:read")]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups("product:read")]
    private ?string $title = null;

    #[ORM\Column]
    #[Groups("product:read")]
    #[Assert\Regex(
        pattern: '/^\d+(\.\d{1,2})?$/',
        message: 'The price must be a valid number with up to 2 decimal places.'
    )]    
    private ?float $price = null;

    #[ORM\Column]
    #[Groups("product:read")]
    #[Assert\Type(type: 'integer', message: 'The quantity must be a valid integer.')]
    private ?int $Qty = null;

    #[ORM\Column(length: 255)]
    #[Groups("product:read")]
    #[Assert\Url(message: 'The image URL "{{ value }}" is not a valid URL.')]
    private ?string $img = null;

    #[ORM\ManyToOne(inversedBy: 'Product')]
    #[Groups("product:read")]
    private ?Category $category = null;

    #[ORM\Column(nullable: true)]
    #[Groups("product:read")]
    #[Assert\Range(
        min: 0,
        max: 5,
        notInRangeMessage : "The rating must be between {{ min }} and {{ max }}",
        invalidMessage : "The rating must be a valid number"
    )]
    private ?int $rating = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString() {
        return $this->title;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQty(): ?int
    {
        return $this->Qty;
    }

    public function setQty(int $Qty): self
    {
        $this->Qty = $Qty;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\Order1Type;
use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\JsonResponse;

#[Route('/order')]
class OrderController extends AbstractController
{
    
    #[Route('/', name: 'app_order_index', methods: ['GET'])]
    public function index(OrderRepository $orderRepository, Request $request): Response
    {
        
    
    
        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }
    #[Route('/filter', name: 'filter',methods:['GET'])]
    public function filter(Request $request, OrderRepository $orderRepository)
    {
        
        $startDate = $request->query->get('start_date');
        $endDate = $request->query->get('end_date');

        if (!$startDate || !$endDate) {
            $startDate = new \DateTimeImmutable('1970-01-01');
            $endDate = new \DateTimeImmutable();
        } else {
            // Convert date strings to DateTime objects
            $startDate = new \DateTimeImmutable($startDate);
            $endDate = new \DateTimeImmutable($endDate);
        }
    

        $orders = $orderRepository->findOrdersByDateRange($startDate, $endDate);
        // $order = $orderRepository->findAll();
        $response = [];
        foreach ($orders as $order) {
            $response[] = [
                'id' => $order->getId(),
                'Adresse' => $order->getAdresse(),
                'time' => $order->getCreatedAt(),
            ];
            
        }
        return new JsonResponse($response);

    }

    #[Route('/new', name: 'app_order_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OrderRepository $orderRepository): Response
    {
        $order = new Order();
        $form = $this->createForm(Order1Type::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $orderRepository->save($order, true);

            return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('order/new.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_show', methods: ['GET'])]
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order' => $order,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_order_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Order $order, OrderRepository $orderRepository): Response
    {
        $form = $this->createForm(Order1Type::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $orderRepository->save($order, true);

            return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('order/edit.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_delete', methods: ['POST'])]
    public function delete(Request $request, Order $order, OrderRepository $orderRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $orderRepository->remove($order, true);
        }

        return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('app_order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/order/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_errors(form.adresse) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/order/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block body %}
<div style="margin-left:400px;margin-top:100px">
    <h1>Edit Order</h1>

    {{ form_start(form) }}
        {{ form_row(form.adresse) }}
     
        <h3>Order Items</h3>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for orderItem in form.orderItem %}
                    <tr>
                        <td>{{ form_row(orderItem.prod) }}</td>
                        <td>{{ form_row(orderItem.Qty) }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr>

        <button type="submit" class="btn btn-primary">Save</button>
    {{ form_end(form) }}
    </div>
{% endblock %}

templates/order/index.html.twig
{% extends 'base-back.html.twig' %}
{% block body %}
    <h1 style="margin-top:100px">Orders</h1>
    <hr>

   
    <div style="margin-left:300px;width:900px" class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 offset-md-3">
      <h1>Filter Orders by Date Range</h1>
      <form id="filter-form">
        <div class="form-group">
          <label for="start-date">Start Date:</label>
          <input type="date" id="start-date" name="start_date" class="form-control">
        </div>
        <div class="form-group">
          <label for="end-date">End Date:</label>
          <input type="date" id="end-date" name="end_date" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Filter</button>
      </form>
      <hr>
      {# <div id="order-list"></div> #}
    </div>
  </div>
</div>

    <table style="margin-left:300px;width:900px" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Total Price</th>
                <th>Created At</th>
                <th>Address</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody >
            {% for order in orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.totalprice }}</td>
                    <td>{{ order.createdAt|date('Y-m-d H:i:s') }}</td>
                    <td>{{ order.adresse }}</td>
                    <td>
                        <a href="{{ path('app_order_show', {'id': order.id}) }}" class="btn btn-primary">Show</a>
                        <a href="{{ path('app_order_edit', {'id': order.id}) }}" class="btn btn-secondary">Edit</a>
                        {{ include('order/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">No orders found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div style="margin-left:500px">

    </div>
{% endblock %}

templates/order/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <div style="margin-top:100px">
    <ul style="margin-top:100px;margin-left:300px ">
        <div style="display:flex">
        <a style="margin-right:20px" href={{path("app_product_index")}}>All products</a>
        <a href={{path("app_product_new")}}>Add product </a>
        
        </div>
    </ul>


    {{ include('product/_form.html.twig') }}

    <a href="{{ path('app_product_index') }}">back to list</a>
    </div>
{% endblock %}

templates/order/panier.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <section class="h-100" style="background-color: #eee;">
        <div class="container h-100 py-5">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-10">

                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <h3 class="fw-normal mb-0 text-black">Achat</h3>
                        <div>

                        </div>
                    </div>

                    {# {% for lc in lignecommandes %} #}
                        <div class="card rounded-3 mb-4">
                            <div class="card-body p-4">
                                <div class="row d-flex justify-content-between align-items-center">
                                    <div class="col-md-2 col-lg-2 col-xl-2">

                                    </div>
                                    <div class="col-md-3 col-lg-3 col-xl-3">
                                        <p class="lead fw-normal mb-2">bla bla</p>
                                        {# <p class="lead fw-normal mb-2">{{ lc.idProduit.nomProduit }}</p> #}

                                    </div>
                                    <div class="col-md-3 col-lg-3 col-xl-2 d-flex">

                                        <h5 class="mb-0">x 5</h5>
                                        {# <h5 class="mb-0">x {{ lc.quantite }}</h5> #}
                                    </div>
                                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                        <h5 class="mb-0">10</h5>
                                        {# <h5 class="mb-0">{{ lc.idProduit.nbPts }}</h5> #}
                                    </div>
                                    <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                        {# <a href="{{ path('app_client_lignecommande_delete', {'idLignecommande': lc.idLignecommande}) }}" class="text-danger"><i class="fas fa-trash fa-lg"></i></a> #}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {# {% else %}
                        <br>
                        <strong>Panier Vide</strong>
                        <br>
                    {% endfor %} #}



                    <div class="card mb-4">
                        <div class="card-body p-4 d-flex flex-row">
                            <div class="form-outline flex-fill">



                                <table class="table">
                                    <tr>
                                        <td width="20%"></td>
                                        <td width="25%">
                                            <h2 class="lead fw-normal mb-2"><strong>total des points: </strong></h2>
                                        </td>
                                        <td>
                                            <h5 class="mb-0">x 2</h5>
                                            {# <h5 class="mb-0">x {{ total_points }}</h5> #}
                                        </td>

                                    </tr>
                                </table>

                            </div>

                        </div>
                    </div>

                    <div class="card">
                        <div class="card-body">
                            <a href="{{ path('app_client_proceed_commande', {'idcommande': idCommande}) }}" class="btn btn-warning btn-block btn-lg">Passer Commande</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block title %}

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

{% endblock %}

templates/order/show.html.twig
{% extends 'base-back.html.twig' %}

{% block body %}
    <h1 style="margin-top:100px;margin-left:500px">Order {{ order.id }}</h1>
    <table style="margin-left:500px">
        <tbody>
            <tr>
                <th>Address</th>
                <td>{{ order.adresse }}</td>
            </tr>
            <tr>
                <th>Total Price</th>
                
            </tr>
            <tr>
                <th>Order Items</th>
                <td>
                    <ul>
                        {% for orderItem in order.orderItem %}
                            <li>
                                {{ orderItem.prod.getTitle() }} - Qty: {{ orderItem.qty }} - Price: {{ orderItem.prod.getPrice() }}
                            </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}